# Generated by Django 5.2.4 on 2025-07-30 11:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=7)),
                ('cor', models.CharField(default='#007bff', help_text='Cor em formato hex (#ffffff)', max_length=7)),
                ('ativa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'unique_together': {('nome', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=10)),
                ('conta', models.CharField(blank=True, max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contas Bancárias',
                'unique_together': {('nome', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='ImportacaoOFX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('total_transacoes', models.IntegerField(default=0)),
                ('transacoes_importadas', models.IntegerField(default=0)),
                ('transacoes_duplicadas', models.IntegerField(default=0)),
                ('sucesso', models.BooleanField(default=True)),
                ('erro', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Importações OFX',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=7)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('identificador_ofx', models.CharField(blank=True, help_text='ID único do OFX para evitar duplicatas', max_length=100)),
                ('importada_ofx', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacoes.categoria')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transacoes.contabancaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transações',
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['usuario', 'data'], name='transacoes__usuario_fccceb_idx'), models.Index(fields=['usuario', 'tipo'], name='transacoes__usuario_0cdab1_idx'), models.Index(fields=['identificador_ofx'], name='transacoes__identif_dddd46_idx')],
            },
        ),
    ]
